name: superuser_interfaces
description: Interface defination for verifying user executes Flutter program with superuser role.
homepage: https://github.com/rk0cc/superuser
repository: https://github.com/rk0cc/superuser/tree/main/superuser_interfaces
version: 2.2.0
environment: 
  sdk: ^3.6.0
resolution: workspace
dependencies: 
  meta: ^1.15.0
dev_dependencies:
  lints: ^5.0.0
platforms:
  linux:
  macos:
  windows:
