name: superuser_interfaces
description: Interface defination for verifying user executes Dart program with superuser role.
homepage: https://github.com/rk0cc/superuser
repository: https://github.com/rk0cc/superuser/tree/current/superuser_interfaces
version: 4.1.0
environment: 
  sdk: ^3.10.0
resolution: workspace
dependencies: 
  meta: ^1.17.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.30.0
platforms:
  linux:
  macos:
  windows:
