name: superuser_plugin_unix
description: "Detect, verify user who execute Flutter program has superuser role in UNIX"
version: 0.1.0
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.2
  superuser_interfaces: ^1.0.0
dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
