name: superuser_plugin_unix
description: "Detect, verify user who execute Dart program has superuser role in UNIX"
version: 4.0.0
homepage: https://github.com/rk0cc/superuser
repository: https://github.com/rk0cc/superuser/tree/current/superuser_plugin_unix
environment:
  sdk: ^3.10.0
resolution: workspace
dependencies:
  ffi: ^2.2.0
  superuser_interfaces: ^4.0.0
dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
hook:
  build: true
