name: superuser_plugin_unix
description: "Detect, verify user who execute Flutter program has superuser role in UNIX"
version: 2.0.0-m.1
homepage: https://github.com/rk0cc/superuser
repository: https://github.com/rk0cc/superuser/tree/main/superuser_plugin_unix
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.2
  superuser_interfaces: ^2.0.0
dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
