// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<SUPERUSER_ERRINFO Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external SUPERUSER_ERRINFO get_uname(ffi.Pointer<ffi.Pointer<ffi.Char>> result);

@ffi.Native<
  SUPERUSER_ERRINFO Function(
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Pointer<gid_t>>,
  )
>()
external SUPERUSER_ERRINFO get_current_user_group(
  ffi.Pointer<ffi.Int> size,
  ffi.Pointer<ffi.Pointer<gid_t>> groups,
);

@ffi.Native<
  SUPERUSER_ERRINFO Function(gid_t, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external SUPERUSER_ERRINFO get_group_name_by_gid(
  int group_id,
  ffi.Pointer<ffi.Pointer<ffi.Char>> result,
);

@ffi.Native<ffi.Bool Function()>()
external bool is_root();

@ffi.Native<SUPERUSER_ERRINFO Function(ffi.Pointer<ffi.Bool>)>()
external SUPERUSER_ERRINFO is_sudo_group(ffi.Pointer<ffi.Bool> result);

@ffi.Native<ffi.Void Function(ffi.Pointer<gid_t>)>()
external void flush_group(ffi.Pointer<gid_t> groups);

typedef gid_t = ffi.UnsignedInt;
typedef ERRCODE = ffi.UnsignedInt;
typedef DartERRCODE = int;

final class _SUPERUSER_ERRINFO extends ffi.Struct {
  @ERRCODE()
  external int code;

  @ffi.Array.multi([129])
  external ffi.Array<ffi.Char> unixapi_func_name;
}

typedef SUPERUSER_ERRINFO = _SUPERUSER_ERRINFO;

const int MAX_UNIX_FUNCNAME_LEN = 129;
