name: superuser
description: Detect, verify user who execute Flutter program has superuser role and running with superuser permission with replicated UNIX identification commands.
version: 2.1.0
homepage: https://github.com/rk0cc/superuser
repository: https://github.com/rk0cc/superuser/tree/main/superuser
funding:
  - https://github.com/sponsors/rk0cc
topics:
  - superuser
  - root
  - admin
  - administrator
  - ffi
environment: 
  sdk: ^3.6.0
  flutter: '>=3.27.0'
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  superuser_interfaces: ^2.1.0
  superuser_plugin_unix: ^2.0.0
  superuser_plugin_windows: ^2.0.0
dev_dependencies:
  flutter_lints: ^5.0.0
platforms:
  linux:
  macos:
  windows:
