// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/superuser_plugin_unix.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
final class SuperuserPluginUnixBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SuperuserPluginUnixBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SuperuserPluginUnixBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Determine user who execute this program is root.
  bool is_root() {
    return _is_root();
  }

  late final _is_rootPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('is_root');
  late final _is_root = _is_rootPtr.asFunction<bool Function()>();

  /// Obtain name of user.
  ffi.Pointer<ffi.Char> get_uname() {
    return _get_uname();
  }

  late final _get_unamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'get_uname');
  late final _get_uname =
      _get_unamePtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}
