name: superuser_plugin_windows
description: "Detect, verify user who execute Flutter program has superuser role in Windows"
version: 2.0.0-m.3
homepage: https://github.com/rk0cc/superuser
repository: https://github.com/rk0cc/superuser/tree/main/superuser_plugin_windows
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  superuser_interfaces: ^2.1.0
dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
