name: superuser_plugin_windows
description: "Detect, verify user who execute Flutter program has superuser role in Windows"
version: 0.1.0
homepage: https://github.com/rk0cc/superuser
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  superuser_interfaces: ^1.0.0
dev_dependencies:
  ffigen: ^12.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
