name: superuser_demo
description: "Flutter superuser package demo application"
publish_to: 'none'
version: 4.1.0
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  superuser:
    path: ../superuser
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
dependency_overrides:
  superuser_plugin_windows:
    path: ../superuser_plugin_windows
  superuser_plugin_unix:
    path: ../superuser_plugin_unix
  superuser_interfaces:
    path: ../superuser_interfaces
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
