// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Bool>)>()
external SUPERUSER_ERRORINFO is_admin_user(ffi.Pointer<ffi.Bool> result);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Bool>)>()
external SUPERUSER_ERRORINFO is_elevated(ffi.Pointer<ffi.Bool> result);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Pointer<ffi.WChar>>)>()
external SUPERUSER_ERRORINFO get_current_username(
  ffi.Pointer<ffi.Pointer<ffi.WChar>> result,
);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.UnsignedLong>)>()
external SUPERUSER_ERRORINFO count_associated_groups_length(
  ffi.Pointer<ffi.UnsignedLong> length,
);

@ffi.Native<
  SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.WChar>>>)
>()
external SUPERUSER_ERRORINFO get_associated_groups(
  ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.WChar>>> groups,
);

typedef ERRCODE = ffi.UnsignedLong;

final class _SUPERUSER_ERRORINFO extends ffi.Struct {
  @ERRCODE()
  external int code;

  @ffi.Array.multi([101])
  external ffi.Array<ffi.WChar> winapi_func_name;
}

typedef SUPERUSER_ERRORINFO = _SUPERUSER_ERRORINFO;

const int MAX_USERNAME_CHAR = 257;

const int WIN32API_FUNC_WLEN = 101;
