// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_field, type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Pointer<ffi.WChar>>)>()
external SUPERUSER_ERRORINFO get_local_machine_name(
  ffi.Pointer<ffi.Pointer<ffi.WChar>> result,
);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Pointer<ffi.WChar>>)>()
external SUPERUSER_ERRORINFO get_current_username(
  ffi.Pointer<ffi.Pointer<ffi.WChar>> result,
);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.UnsignedLong>)>()
external SUPERUSER_ERRORINFO count_associated_groups_length(
  ffi.Pointer<ffi.UnsignedLong> length,
);

@ffi.Native<
  SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Pointer<WINDOWS_GROUP_NAME>>)
>()
external SUPERUSER_ERRORINFO get_associated_groups(
  ffi.Pointer<ffi.Pointer<WINDOWS_GROUP_NAME>> groups,
);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Bool>)>()
external SUPERUSER_ERRORINFO is_admin_user(ffi.Pointer<ffi.Bool> result);

@ffi.Native<SUPERUSER_ERRORINFO Function(ffi.Pointer<ffi.Bool>)>()
external SUPERUSER_ERRORINFO is_elevated(ffi.Pointer<ffi.Bool> result);

sealed class _SID_NAME_USE {
  static const SidTypeUser = 1;
  static const SidTypeGroup = 2;
  static const SidTypeDomain = 3;
  static const SidTypeAlias = 4;
  static const SidTypeWellKnownGroup = 5;
  static const SidTypeDeletedAccount = 6;
  static const SidTypeInvalid = 7;
  static const SidTypeUnknown = 8;
  static const SidTypeComputer = 9;
  static const SidTypeLabel = 10;
  static const SidTypeLogonSession = 11;
}

typedef SID_NAME_USE = _SID_NAME_USE;

typedef ERRCODE = ffi.UnsignedLong;

final class _SUPERUSER_ERRORINFO extends ffi.Struct {
  @ERRCODE()
  external int code;

  @ffi.Array.multi([129])
  external ffi.Array<ffi.WChar> winapi_func_name;
}

typedef SUPERUSER_ERRORINFO = _SUPERUSER_ERRORINFO;

final class _WINDOWS_GROUP_NAME extends ffi.Struct {
  @ffi.Array.multi([257])
  external ffi.Array<ffi.WChar> name;

  @ffi.Array.multi([257])
  external ffi.Array<ffi.WChar> domain;

  @ffi.UnsignedInt()
  external int group_type;
}

typedef WINDOWS_GROUP_NAME = _WINDOWS_GROUP_NAME;

const int MAX_USERNAME_CHAR = 257;

const int WIN32API_FUNC_WLEN = 129;

const int NETBIOS_NAME_LEN = 16;
